name: Build and Push Docker Image          # Name of the workflow
on:
  push:
    branches: [master]                       # Trigger this workflow on push to main branch

jobs:
  docker:
    runs-on: ubuntu-latest                 # Use the latest Ubuntu GitHub-hosted runner

    steps:
      - uses: actions/checkout@v4          # Step 1: Checkout the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Step 2: Enable Docker Buildx (for advanced builds)

      - name: Login to DockerHub
        uses: docker/login-action@v3         # Step 3: Authenticate with DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Use your DockerHub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}   # Use your DockerHub password/token stored in GitHub Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v5   # Step 4: Build the Docker image and push to DockerHub
        with:
          context: .                        # Build context is current directory
          push: true                        # Push image after build completes
          tags: melmenshawy24/ci-cd-python-demo:latest  # Replace with your actual DockerHub repo/tag
