# Name of the GitHub Actions workflow shown in the Actions tab
name: First CI Pipeline

# Trigger this workflow on every push to the repository
on: [push]

jobs:
  # Define a job named 'greet'
  greet:
    # Run this job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v4  # GitHub-provided action to pull your repo into the runner

      # Step 2: Print a message to the workflow log
      - name: Say Hello
        run: echo "Hello from your first GitHub Action!"  # Executes a shell command
